#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "lexer"
  require "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 114)
  def parse(code, show_tokens=false)
    @tokens = Flair::Lexer.new(code).tokenize
    puts @tokens.inspect if show_tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     6,     8,    22,    11,    13,    15,    17,    19,     1,
     2,     4,     6,     8,    25,    11,    13,    15,    17,    19,
     1,     2,     4,     6,     8,    29,    11,    13,    15,    17,
    19,     1,     2,    23,    30,    28,     4,     6,     8,    33,
    11,    13,    15,    17,    19,     1,     2,     4,     6,     8,
    37,    11,    13,    15,    17,    19,     1,     2,     4,     6,
     8,    29,    11,    13,    15,    17,    19,     1,     2,    33,
    41,    28,    30,    26,    39,    30,    30,    21,    30,    33 ]

racc_action_check = [
     0,     0,     0,     2,     0,     0,     0,     0,     0,     0,
     0,    33,    33,    33,     8,    33,    33,    33,    33,    33,
    33,    33,    27,    27,    27,    18,    27,    27,    27,    27,
    27,    27,    27,     4,    20,    18,     6,     6,     6,    25,
     6,     6,     6,     6,     6,     6,     6,    22,    22,    22,
    26,    22,    22,    22,    22,    22,    22,    22,    21,    21,
    21,    40,    21,    21,    21,    21,    21,    21,    21,    24,
    40,    40,    24,    16,    30,    31,    32,     1,    38,    23 ]

racc_action_pointer = [
    -2,    60,   -14,   nil,    21,   nil,    34,   nil,     2,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    73,   nil,    20,   nil,
    18,    56,    45,    66,    56,    26,    50,    20,   nil,   nil,
    63,    59,    60,     9,   nil,   nil,   nil,   nil,    62,   nil,
    56,   nil ]

racc_action_default = [
    -1,   -20,   -22,    -6,   -29,    -7,   -29,    -8,   -29,    -9,
   -10,   -15,   -11,   -16,   -12,   -17,   -29,   -18,    -2,   -19,
    -3,   -29,   -29,   -29,   -29,   -29,   -29,    -5,   -14,   -13,
   -29,   -23,   -24,   -29,   -25,   -27,   -26,    42,    -4,   -21,
   -29,   -28 ]

racc_goto_table = [
    18,    24,    34,    35,    36,    16,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    31,    32,   nil,   nil,
   nil,   nil,    38,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    40 ]

racc_goto_check = [
     2,     3,    12,    12,    12,     1,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,     3,   nil,   nil,
   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     5,     0,    -5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -21 ]

racc_goto_default = [
   nil,   nil,   nil,    20,    27,     3,     5,     7,     9,    10,
    12,    14,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 19, :_reduce_1,
  1, 19, :_reduce_2,
  1, 20, :_reduce_3,
  3, 20, :_reduce_4,
  2, 20, :_reduce_5,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 23, :_reduce_15,
  1, 23, :_reduce_16,
  1, 23, :_reduce_17,
  1, 23, :_reduce_18,
  1, 23, :_reduce_19,
  1, 24, :_reduce_20,
  3, 24, :_reduce_21,
  1, 25, :_reduce_22,
  3, 26, :_reduce_23,
  3, 26, :_reduce_24,
  3, 27, :_reduce_25,
  3, 28, :_reduce_26,
  3, 29, :_reduce_27,
  3, 30, :_reduce_28 ]

racc_reduce_n = 29

racc_shift_n = 42

racc_token_table = {
  false => 0,
  :error => 1,
  :CLASS => 2,
  :IF => 3,
  :ID => 4,
  :NEWLINE => 5,
  :NUMBER => 6,
  :STRING => 7,
  :TRUE => 8,
  :FALSE => 9,
  :NIL => 10,
  :IDENTIFIER => 11,
  :CONSTANT => 12,
  :INDENT => 13,
  :DEDENT => 14,
  ";" => 15,
  "." => 16,
  "=" => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "CLASS",
  "IF",
  "ID",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "INDENT",
  "DEDENT",
  "\";\"",
  "\".\"",
  "\"=\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Constant",
  "Assign",
  "Class",
  "Id",
  "If",
  "Block" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 18)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 19)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 25)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 26)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_5(val, _values, result)
     result = Nodes.new([val[0]]) 
    result
  end
.,.,

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'grammar.y', 50)
  def _reduce_15(val, _values, result)
     result = LiteralNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 51)
  def _reduce_16(val, _values, result)
     result = LiteralNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_17(val, _values, result)
     result = LiteralNode.new(true) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 53)
  def _reduce_18(val, _values, result)
     result = LiteralNode.new(false) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 54)
  def _reduce_19(val, _values, result)
     result = LiteralNode.new(nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 60)
  def _reduce_20(val, _values, result)
     result = CallNode.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 62)
  def _reduce_21(val, _values, result)
     result = CallNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 70)
  def _reduce_22(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 75)
  def _reduce_23(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 77)
  def _reduce_24(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_25(val, _values, result)
     result = ClassNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 89)
  def _reduce_26(val, _values, result)
     result = IdNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 94)
  def _reduce_27(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 102)
  def _reduce_28(val, _values, result)
     result = val[1] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
